version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    expose:
      - 6379
    ports:
      - 6379:6379
  nodejs:
    depends_on: 
      - redis 
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - REDIS_URL=redis://cache
    links:
      - redis
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: sh -c "npm run start;"
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=isa_db
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - 27018:27017

      
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: